### ISSUE TITLE
Docker-based Project Isolation

### ISSUE THREAD

**Issue by Santos-Enoque** [Santos-Enoque/magents#2]
## Overview
Implement Docker containers for complete project isolation to prevent cross-project interference when running multiple Claude Code agents on different projects simultaneously.

## Problem
- Multiple Next.js projects compete for the same ports (e.g., port 3000)
- Claude Code agents get confused seeing servers from other projects
- File system access can cross project boundaries
- No resource isolation between projects

## Proposed Solution
Implement Docker-based isolation where each project runs in its own container with:
- Isolated network namespace
- Isolated filesystem
- Dedicated port ranges
- Resource limits

### 1. Dockerfile Creation
```dockerfile
FROM node:20-slim
RUN apt-get update && apt-get install -y git tmux
WORKDIR /workspace
```

### 2. Docker Compose Template
```yaml
services:
  project-dev:
    build: .
    volumes:
      - .:/workspace
      - ~/.claude:/home/user/.claude
    ports:
      - "3000-3010:3000-3010"
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
```

### 3. Container Management Service
- Create `DockerService` class similar to `TmuxService`
- Handle container lifecycle (create, start, stop, remove)
- Volume mounting for project files and Claude settings

## Benefits
- Complete project isolation
- No port conflicts
- Clear project boundaries for agents
- Better resource management
- Easy cleanup

## Tasks
- [ ] Create Dockerfile template
- [ ] Implement DockerService class
- [ ] Add docker-compose generation
- [ ] Update CLI commands for Docker mode
- [ ] Add container health checks
- [ ] Document Docker requirements
