### ISSUE TITLE
Intelligent Port Management

### ISSUE THREAD

**Issue by Santos-Enoque** [Santos-Enoque/magents#4]
## Overview
Implement smart port allocation and management to prevent conflicts when running multiple projects with web services.

## Problem
- Multiple Next.js/web projects default to port 3000
- Manual port configuration is error-prone
- No visibility into port usage
- Services within projects may need multiple ports

### 1. Dynamic Port Allocation
```typescript
class PortManager {
  private usedPorts: Map<string, number[]>;
  
  allocatePort(projectId: string, preferred?: number): number;
  allocateRange(projectId: string, count: number): [number, number];
  releaseProjectPorts(projectId: string): void;
}
```

### 2. Port Mapping Configuration
```yaml
# Project config
ports:
  web: 3000      # Internal port
  api: 4000      # Internal port
  mapped:
    web: 8080    # External port
    api: 8081    # External port
```

### 3. Service Discovery
- Automatic port detection from package.json scripts
- Environment variable injection for port configuration
- Update running services when ports change

### Port Allocation Strategy
1. Check if preferred port is available
2. Find next available port in range
3. Reserve port for project lifetime
4. Support named port mappings

### Integration Points
- Docker port mapping
- Environment variable injection
- Service health checks
- Port conflict resolution

## Benefits
- Zero port conflicts
- Automatic allocation
- Better developer experience
- Support for multi-service projects

## Tasks
- [ ] Implement PortManager service
- [ ] Add port detection from package.json
- [ ] Create port mapping UI/CLI
- [ ] Add port health checks
- [ ] Document port configuration
- [ ] Add port reservation system
